# Generated by Django 4.2.10 on 2024-06-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_adminsuser_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminsuser',
            name='type',
            field=models.CharField(choices=[('admin', 'Admin'), ('secretar', 'Secretar')], max_length=200),
        ),
    ]
