# Generated by Django 3.2.13 on 2024-06-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_alter_adminsuser_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminsuser',
            name='type',
            field=models.CharField(choices=[('headadmin', 'HeadAdmin'), ('sales', 'Sales'), ('doctor', 'Doctor'), ('admin', 'Admin')], max_length=200),
        ),
    ]
