# Generated by Django 3.2.13 on 2024-06-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=13)),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=300)),
                ('type', models.CharField(choices=[('headadmin', 'HeadAdmin'), ('sales', 'Sales'), ('doctor', 'Doctor'), ('admin', 'Admin')], max_length=200)),
            ],
        ),
    ]
