# Generated by Django 3.2.13 on 2024-06-28 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminsUser',
            new_name='BoosUser',
        ),
    ]
